apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    env: production  
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      env: production
  template: 
    metadata: 
      labels: 
        app: postgres
        env: production
    spec: 
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_PASSWORD
              value: 1Qaz2Wsx
            - name: PGDATA
              value: /var/lib/postgresql/data/postgresql-01
          volumeMounts:
            - name: postgres-persistent-storage
              mountPath: /var/lib/postgresql/data/    
      volumes: 
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: postgresql-pvc
        
